### CREATE A CAT:
POST http://localhost:3900/api/cats
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>
Content-Type: application/json

{
  "name": "Whiskers",
  "age": 3,
  "breed": "Siamese"
}


### GET ALL CATS:
GET http://localhost:3900/api/cats
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>


### GET A CAT BY ID:
GET http://localhost:3900/api/cats/{cat-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>

### UPDATE A CAT:
PUT http://localhost:3900/api/cats/{cat-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>
Content-Type: application/json

{
  "name": "Whiskers",
  "age": 3,
  "breed": "Siamese",
  "color": "White",
  "gender": "Male"
}


### DELETE A CAT:
DELETE http://localhost:3900/api/cats/{cat-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>

