import { Injectable } from '@nestjs/common';

export interface ResidentScholarProfile {
  residentId: string;
  studentId: string;
  studentFullName: string;
  admissionNo: string;
  gradeLevel: string;
  dormWing: 'ALPHA_BOYS_WING' | 'BETA_GIRLS_WING' | 'HONORS_SCHOLARS_HALL';
  roomNumber: string;
  bedAssignment: string;
  roommateNames: string[];
  floorWardenName: string;
  dietaryRestrictions: 'VEGETARIAN' | 'HALAL' | 'VEGAN' | 'NO_RESTRICTIONS';
  curfewPermitTier: 'STANDARD_1900' | 'SENIOR_2100';
  emergencyGuardianPhone: string;
}

export const MASTER_DORMITORY_ROSTER: ResidentScholarProfile[] = [
  {
    residentId: "DORM-RES-0001",
    studentId: "std-0001",
    studentFullName: "Residential Scholar 1",
    admissionNo: "ADM-2025-0001",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-101",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0001"
  },
  {
    residentId: "DORM-RES-0002",
    studentId: "std-0002",
    studentFullName: "Residential Scholar 2",
    admissionNo: "ADM-2025-0002",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-101",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0002"
  },
  {
    residentId: "DORM-RES-0003",
    studentId: "std-0003",
    studentFullName: "Residential Scholar 3",
    admissionNo: "ADM-2025-0003",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-101",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0003"
  },
  {
    residentId: "DORM-RES-0004",
    studentId: "std-0004",
    studentFullName: "Residential Scholar 4",
    admissionNo: "ADM-2025-0004",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-102",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0004"
  },
  {
    residentId: "DORM-RES-0005",
    studentId: "std-0005",
    studentFullName: "Residential Scholar 5",
    admissionNo: "ADM-2025-0005",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-102",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0005"
  },
  {
    residentId: "DORM-RES-0006",
    studentId: "std-0006",
    studentFullName: "Residential Scholar 6",
    admissionNo: "ADM-2025-0006",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-102",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0006"
  },
  {
    residentId: "DORM-RES-0007",
    studentId: "std-0007",
    studentFullName: "Residential Scholar 7",
    admissionNo: "ADM-2025-0007",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-102",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0007"
  },
  {
    residentId: "DORM-RES-0008",
    studentId: "std-0008",
    studentFullName: "Residential Scholar 8",
    admissionNo: "ADM-2025-0008",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-103",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0008"
  },
  {
    residentId: "DORM-RES-0009",
    studentId: "std-0009",
    studentFullName: "Residential Scholar 9",
    admissionNo: "ADM-2025-0009",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-103",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0009"
  },
  {
    residentId: "DORM-RES-0010",
    studentId: "std-0010",
    studentFullName: "Residential Scholar 10",
    admissionNo: "ADM-2025-0010",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-103",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0010"
  },
  {
    residentId: "DORM-RES-0011",
    studentId: "std-0011",
    studentFullName: "Residential Scholar 11",
    admissionNo: "ADM-2025-0011",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-103",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0011"
  },
  {
    residentId: "DORM-RES-0012",
    studentId: "std-0012",
    studentFullName: "Residential Scholar 12",
    admissionNo: "ADM-2025-0012",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-104",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0012"
  },
  {
    residentId: "DORM-RES-0013",
    studentId: "std-0013",
    studentFullName: "Residential Scholar 13",
    admissionNo: "ADM-2025-0013",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-104",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0013"
  },
  {
    residentId: "DORM-RES-0014",
    studentId: "std-0014",
    studentFullName: "Residential Scholar 14",
    admissionNo: "ADM-2025-0014",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-104",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0014"
  },
  {
    residentId: "DORM-RES-0015",
    studentId: "std-0015",
    studentFullName: "Residential Scholar 15",
    admissionNo: "ADM-2025-0015",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-104",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0015"
  },
  {
    residentId: "DORM-RES-0016",
    studentId: "std-0016",
    studentFullName: "Residential Scholar 16",
    admissionNo: "ADM-2025-0016",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-105",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0016"
  },
  {
    residentId: "DORM-RES-0017",
    studentId: "std-0017",
    studentFullName: "Residential Scholar 17",
    admissionNo: "ADM-2025-0017",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-105",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0017"
  },
  {
    residentId: "DORM-RES-0018",
    studentId: "std-0018",
    studentFullName: "Residential Scholar 18",
    admissionNo: "ADM-2025-0018",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-105",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0018"
  },
  {
    residentId: "DORM-RES-0019",
    studentId: "std-0019",
    studentFullName: "Residential Scholar 19",
    admissionNo: "ADM-2025-0019",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-105",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0019"
  },
  {
    residentId: "DORM-RES-0020",
    studentId: "std-0020",
    studentFullName: "Residential Scholar 20",
    admissionNo: "ADM-2025-0020",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-106",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0020"
  },
  {
    residentId: "DORM-RES-0021",
    studentId: "std-0021",
    studentFullName: "Residential Scholar 21",
    admissionNo: "ADM-2025-0021",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-106",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0021"
  },
  {
    residentId: "DORM-RES-0022",
    studentId: "std-0022",
    studentFullName: "Residential Scholar 22",
    admissionNo: "ADM-2025-0022",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-106",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0022"
  },
  {
    residentId: "DORM-RES-0023",
    studentId: "std-0023",
    studentFullName: "Residential Scholar 23",
    admissionNo: "ADM-2025-0023",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-106",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0023"
  },
  {
    residentId: "DORM-RES-0024",
    studentId: "std-0024",
    studentFullName: "Residential Scholar 24",
    admissionNo: "ADM-2025-0024",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-107",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0024"
  },
  {
    residentId: "DORM-RES-0025",
    studentId: "std-0025",
    studentFullName: "Residential Scholar 25",
    admissionNo: "ADM-2025-0025",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-107",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0025"
  },
  {
    residentId: "DORM-RES-0026",
    studentId: "std-0026",
    studentFullName: "Residential Scholar 26",
    admissionNo: "ADM-2025-0026",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-107",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0026"
  },
  {
    residentId: "DORM-RES-0027",
    studentId: "std-0027",
    studentFullName: "Residential Scholar 27",
    admissionNo: "ADM-2025-0027",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-107",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0027"
  },
  {
    residentId: "DORM-RES-0028",
    studentId: "std-0028",
    studentFullName: "Residential Scholar 28",
    admissionNo: "ADM-2025-0028",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-108",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0028"
  },
  {
    residentId: "DORM-RES-0029",
    studentId: "std-0029",
    studentFullName: "Residential Scholar 29",
    admissionNo: "ADM-2025-0029",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-108",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0029"
  },
  {
    residentId: "DORM-RES-0030",
    studentId: "std-0030",
    studentFullName: "Residential Scholar 30",
    admissionNo: "ADM-2025-0030",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-108",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0030"
  },
  {
    residentId: "DORM-RES-0031",
    studentId: "std-0031",
    studentFullName: "Residential Scholar 31",
    admissionNo: "ADM-2025-0031",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-108",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0031"
  },
  {
    residentId: "DORM-RES-0032",
    studentId: "std-0032",
    studentFullName: "Residential Scholar 32",
    admissionNo: "ADM-2025-0032",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-109",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0032"
  },
  {
    residentId: "DORM-RES-0033",
    studentId: "std-0033",
    studentFullName: "Residential Scholar 33",
    admissionNo: "ADM-2025-0033",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-109",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0033"
  },
  {
    residentId: "DORM-RES-0034",
    studentId: "std-0034",
    studentFullName: "Residential Scholar 34",
    admissionNo: "ADM-2025-0034",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-109",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0034"
  },
  {
    residentId: "DORM-RES-0035",
    studentId: "std-0035",
    studentFullName: "Residential Scholar 35",
    admissionNo: "ADM-2025-0035",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-109",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0035"
  },
  {
    residentId: "DORM-RES-0036",
    studentId: "std-0036",
    studentFullName: "Residential Scholar 36",
    admissionNo: "ADM-2025-0036",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-110",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0036"
  },
  {
    residentId: "DORM-RES-0037",
    studentId: "std-0037",
    studentFullName: "Residential Scholar 37",
    admissionNo: "ADM-2025-0037",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-110",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0037"
  },
  {
    residentId: "DORM-RES-0038",
    studentId: "std-0038",
    studentFullName: "Residential Scholar 38",
    admissionNo: "ADM-2025-0038",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-110",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0038"
  },
  {
    residentId: "DORM-RES-0039",
    studentId: "std-0039",
    studentFullName: "Residential Scholar 39",
    admissionNo: "ADM-2025-0039",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-110",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0039"
  },
  {
    residentId: "DORM-RES-0040",
    studentId: "std-0040",
    studentFullName: "Residential Scholar 40",
    admissionNo: "ADM-2025-0040",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-111",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0040"
  },
  {
    residentId: "DORM-RES-0041",
    studentId: "std-0041",
    studentFullName: "Residential Scholar 41",
    admissionNo: "ADM-2025-0041",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-111",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0041"
  },
  {
    residentId: "DORM-RES-0042",
    studentId: "std-0042",
    studentFullName: "Residential Scholar 42",
    admissionNo: "ADM-2025-0042",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-111",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0042"
  },
  {
    residentId: "DORM-RES-0043",
    studentId: "std-0043",
    studentFullName: "Residential Scholar 43",
    admissionNo: "ADM-2025-0043",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-111",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0043"
  },
  {
    residentId: "DORM-RES-0044",
    studentId: "std-0044",
    studentFullName: "Residential Scholar 44",
    admissionNo: "ADM-2025-0044",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-112",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0044"
  },
  {
    residentId: "DORM-RES-0045",
    studentId: "std-0045",
    studentFullName: "Residential Scholar 45",
    admissionNo: "ADM-2025-0045",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-112",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0045"
  },
  {
    residentId: "DORM-RES-0046",
    studentId: "std-0046",
    studentFullName: "Residential Scholar 46",
    admissionNo: "ADM-2025-0046",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-112",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0046"
  },
  {
    residentId: "DORM-RES-0047",
    studentId: "std-0047",
    studentFullName: "Residential Scholar 47",
    admissionNo: "ADM-2025-0047",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-112",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0047"
  },
  {
    residentId: "DORM-RES-0048",
    studentId: "std-0048",
    studentFullName: "Residential Scholar 48",
    admissionNo: "ADM-2025-0048",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-113",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0048"
  },
  {
    residentId: "DORM-RES-0049",
    studentId: "std-0049",
    studentFullName: "Residential Scholar 49",
    admissionNo: "ADM-2025-0049",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-113",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0049"
  },
  {
    residentId: "DORM-RES-0050",
    studentId: "std-0050",
    studentFullName: "Residential Scholar 50",
    admissionNo: "ADM-2025-0050",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-113",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0050"
  },
  {
    residentId: "DORM-RES-0051",
    studentId: "std-0051",
    studentFullName: "Residential Scholar 51",
    admissionNo: "ADM-2025-0051",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-113",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0051"
  },
  {
    residentId: "DORM-RES-0052",
    studentId: "std-0052",
    studentFullName: "Residential Scholar 52",
    admissionNo: "ADM-2025-0052",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-114",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0052"
  },
  {
    residentId: "DORM-RES-0053",
    studentId: "std-0053",
    studentFullName: "Residential Scholar 53",
    admissionNo: "ADM-2025-0053",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-114",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0053"
  },
  {
    residentId: "DORM-RES-0054",
    studentId: "std-0054",
    studentFullName: "Residential Scholar 54",
    admissionNo: "ADM-2025-0054",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-114",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0054"
  },
  {
    residentId: "DORM-RES-0055",
    studentId: "std-0055",
    studentFullName: "Residential Scholar 55",
    admissionNo: "ADM-2025-0055",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-114",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0055"
  },
  {
    residentId: "DORM-RES-0056",
    studentId: "std-0056",
    studentFullName: "Residential Scholar 56",
    admissionNo: "ADM-2025-0056",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-115",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0056"
  },
  {
    residentId: "DORM-RES-0057",
    studentId: "std-0057",
    studentFullName: "Residential Scholar 57",
    admissionNo: "ADM-2025-0057",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-115",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0057"
  },
  {
    residentId: "DORM-RES-0058",
    studentId: "std-0058",
    studentFullName: "Residential Scholar 58",
    admissionNo: "ADM-2025-0058",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-115",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0058"
  },
  {
    residentId: "DORM-RES-0059",
    studentId: "std-0059",
    studentFullName: "Residential Scholar 59",
    admissionNo: "ADM-2025-0059",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-115",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0059"
  },
  {
    residentId: "DORM-RES-0060",
    studentId: "std-0060",
    studentFullName: "Residential Scholar 60",
    admissionNo: "ADM-2025-0060",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-116",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0060"
  },
  {
    residentId: "DORM-RES-0061",
    studentId: "std-0061",
    studentFullName: "Residential Scholar 61",
    admissionNo: "ADM-2025-0061",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-116",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0061"
  },
  {
    residentId: "DORM-RES-0062",
    studentId: "std-0062",
    studentFullName: "Residential Scholar 62",
    admissionNo: "ADM-2025-0062",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-116",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0062"
  },
  {
    residentId: "DORM-RES-0063",
    studentId: "std-0063",
    studentFullName: "Residential Scholar 63",
    admissionNo: "ADM-2025-0063",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-116",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0063"
  },
  {
    residentId: "DORM-RES-0064",
    studentId: "std-0064",
    studentFullName: "Residential Scholar 64",
    admissionNo: "ADM-2025-0064",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-117",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0064"
  },
  {
    residentId: "DORM-RES-0065",
    studentId: "std-0065",
    studentFullName: "Residential Scholar 65",
    admissionNo: "ADM-2025-0065",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-117",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0065"
  },
  {
    residentId: "DORM-RES-0066",
    studentId: "std-0066",
    studentFullName: "Residential Scholar 66",
    admissionNo: "ADM-2025-0066",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-117",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0066"
  },
  {
    residentId: "DORM-RES-0067",
    studentId: "std-0067",
    studentFullName: "Residential Scholar 67",
    admissionNo: "ADM-2025-0067",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-117",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0067"
  },
  {
    residentId: "DORM-RES-0068",
    studentId: "std-0068",
    studentFullName: "Residential Scholar 68",
    admissionNo: "ADM-2025-0068",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-118",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0068"
  },
  {
    residentId: "DORM-RES-0069",
    studentId: "std-0069",
    studentFullName: "Residential Scholar 69",
    admissionNo: "ADM-2025-0069",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-118",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0069"
  },
  {
    residentId: "DORM-RES-0070",
    studentId: "std-0070",
    studentFullName: "Residential Scholar 70",
    admissionNo: "ADM-2025-0070",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-118",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0070"
  },
  {
    residentId: "DORM-RES-0071",
    studentId: "std-0071",
    studentFullName: "Residential Scholar 71",
    admissionNo: "ADM-2025-0071",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-118",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0071"
  },
  {
    residentId: "DORM-RES-0072",
    studentId: "std-0072",
    studentFullName: "Residential Scholar 72",
    admissionNo: "ADM-2025-0072",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-119",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0072"
  },
  {
    residentId: "DORM-RES-0073",
    studentId: "std-0073",
    studentFullName: "Residential Scholar 73",
    admissionNo: "ADM-2025-0073",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-119",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0073"
  },
  {
    residentId: "DORM-RES-0074",
    studentId: "std-0074",
    studentFullName: "Residential Scholar 74",
    admissionNo: "ADM-2025-0074",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-119",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0074"
  },
  {
    residentId: "DORM-RES-0075",
    studentId: "std-0075",
    studentFullName: "Residential Scholar 75",
    admissionNo: "ADM-2025-0075",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-119",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "HALAL",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0075"
  },
  {
    residentId: "DORM-RES-0076",
    studentId: "std-0076",
    studentFullName: "Residential Scholar 76",
    admissionNo: "ADM-2025-0076",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-120",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0076"
  },
  {
    residentId: "DORM-RES-0077",
    studentId: "std-0077",
    studentFullName: "Residential Scholar 77",
    admissionNo: "ADM-2025-0077",
    gradeLevel: "Grade 10",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-120",
    bedAssignment: "BED-2",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0077"
  },
  {
    residentId: "DORM-RES-0078",
    studentId: "std-0078",
    studentFullName: "Residential Scholar 78",
    admissionNo: "ADM-2025-0078",
    gradeLevel: "Grade 11",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-120",
    bedAssignment: "BED-3",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0078"
  },
  {
    residentId: "DORM-RES-0079",
    studentId: "std-0079",
    studentFullName: "Residential Scholar 79",
    admissionNo: "ADM-2025-0079",
    gradeLevel: "Grade 12",
    dormWing: "BETA_GIRLS_WING",
    roomNumber: "RM-120",
    bedAssignment: "BED-4",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mrs. Helena Vance",
    dietaryRestrictions: "NO_RESTRICTIONS",
    curfewPermitTier: "SENIOR_2100",
    emergencyGuardianPhone: "+1 (555) 500-0079"
  },
  {
    residentId: "DORM-RES-0080",
    studentId: "std-0080",
    studentFullName: "Residential Scholar 80",
    admissionNo: "ADM-2025-0080",
    gradeLevel: "Grade 9",
    dormWing: "ALPHA_BOYS_WING",
    roomNumber: "RM-121",
    bedAssignment: "BED-1",
    roommateNames: ["Peer Scholar A", "Peer Scholar B"],
    floorWardenName: "Mr. Patrick O Connor",
    dietaryRestrictions: "VEGETARIAN",
    curfewPermitTier: "STANDARD_1900",
    emergencyGuardianPhone: "+1 (555) 500-0080"
  },
];

@Injectable()
export class DormitoryRosterMasterService {
  public getAllResidents(): ResidentScholarProfile[] {
    return MASTER_DORMITORY_ROSTER;
  }

  public getResidentsByWing(wing: ResidentScholarProfile['dormWing']): ResidentScholarProfile[] {
    return MASTER_DORMITORY_ROSTER.filter(r => r.dormWing === wing);
  }
}
