import { Injectable } from '@nestjs/common';

export interface ComprehensiveLibraryBook {
  isbn: string;
  deweyDecimalCode: string;
  bookTitle: string;
  primaryAuthor: string;
  coAuthors: string[];
  publisherName: string;
  editionYear: number;
  totalPrintCopies: number;
  availableCopies: number;
  rackLocation: string;
  academicSubjectCategory: 'PHYSICS' | 'MATHEMATICS' | 'CHEMISTRY' | 'BIOLOGY' | 'COMPUTER_SCIENCE' | 'WORLD_LITERATURE' | 'HISTORY' | 'ECONOMICS' | 'PHILOSOPHY' | 'GENERAL_REFERENCE';
  summarySynopsis: string;
}

export const MASTER_LIBRARY_BOOKS_CATALOG: ComprehensiveLibraryBook[] = [
  {
    isbn: "978-0-100293-X",
    deweyDecimalCode: "504.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 1",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-100586-X",
    deweyDecimalCode: "509.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 1",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-100879-X",
    deweyDecimalCode: "513.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 1",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-101172-X",
    deweyDecimalCode: "518.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 1",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-101465-X",
    deweyDecimalCode: "522.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 1",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-101758-X",
    deweyDecimalCode: "527.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 1",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-102051-X",
    deweyDecimalCode: "531.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 1",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-102344-X",
    deweyDecimalCode: "536.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 1",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-102637-X",
    deweyDecimalCode: "540.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 1",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-102930-X",
    deweyDecimalCode: "545.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 2",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-103223-X",
    deweyDecimalCode: "549.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 2",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-103516-X",
    deweyDecimalCode: "554.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 2",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-103809-X",
    deweyDecimalCode: "558.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 2",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-104102-X",
    deweyDecimalCode: "563.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 2",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-104395-X",
    deweyDecimalCode: "567.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 2",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-104688-X",
    deweyDecimalCode: "572.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 2",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-104981-X",
    deweyDecimalCode: "576.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 2",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-105274-X",
    deweyDecimalCode: "581.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 2",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-105567-X",
    deweyDecimalCode: "585.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 2",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-105860-X",
    deweyDecimalCode: "590.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 3",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-106153-X",
    deweyDecimalCode: "594.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 3",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-106446-X",
    deweyDecimalCode: "599.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 3",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-106739-X",
    deweyDecimalCode: "603.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 3",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-107032-X",
    deweyDecimalCode: "608.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 3",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-107325-X",
    deweyDecimalCode: "612.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 3",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-107618-X",
    deweyDecimalCode: "617.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 3",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-107911-X",
    deweyDecimalCode: "621.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 3",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-108204-X",
    deweyDecimalCode: "626.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 3",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-108497-X",
    deweyDecimalCode: "630.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 3",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-108790-X",
    deweyDecimalCode: "635.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 4",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-109083-X",
    deweyDecimalCode: "639.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 4",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-109376-X",
    deweyDecimalCode: "644.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 4",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-109669-X",
    deweyDecimalCode: "648.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 4",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-109962-X",
    deweyDecimalCode: "653.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 4",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-110255-X",
    deweyDecimalCode: "657.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 4",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-110548-X",
    deweyDecimalCode: "662.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 4",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-110841-X",
    deweyDecimalCode: "666.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 4",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-111134-X",
    deweyDecimalCode: "671.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 4",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-111427-X",
    deweyDecimalCode: "675.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 4",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-111720-X",
    deweyDecimalCode: "680.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 5",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-112013-X",
    deweyDecimalCode: "684.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 5",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-112306-X",
    deweyDecimalCode: "689.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 5",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-112599-X",
    deweyDecimalCode: "693.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 5",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-112892-X",
    deweyDecimalCode: "698.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 5",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-113185-X",
    deweyDecimalCode: "702.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 5",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-113478-X",
    deweyDecimalCode: "707.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 5",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-113771-X",
    deweyDecimalCode: "711.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 5",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-114064-X",
    deweyDecimalCode: "716.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 5",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-114357-X",
    deweyDecimalCode: "720.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 5",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-114650-X",
    deweyDecimalCode: "725.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 6",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-114943-X",
    deweyDecimalCode: "729.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 6",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-115236-X",
    deweyDecimalCode: "734.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 6",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-115529-X",
    deweyDecimalCode: "738.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 6",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-115822-X",
    deweyDecimalCode: "743.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 6",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-116115-X",
    deweyDecimalCode: "747.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 6",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-116408-X",
    deweyDecimalCode: "752.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 6",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-116701-X",
    deweyDecimalCode: "756.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 6",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-116994-X",
    deweyDecimalCode: "761.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 6",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-117287-X",
    deweyDecimalCode: "765.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 6",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-117580-X",
    deweyDecimalCode: "770.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 7",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-117873-X",
    deweyDecimalCode: "774.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 7",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-118166-X",
    deweyDecimalCode: "779.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 7",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-118459-X",
    deweyDecimalCode: "783.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 7",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-118752-X",
    deweyDecimalCode: "788.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 7",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-119045-X",
    deweyDecimalCode: "792.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 7",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-119338-X",
    deweyDecimalCode: "797.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 7",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-119631-X",
    deweyDecimalCode: "801.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 7",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-119924-X",
    deweyDecimalCode: "806.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 7",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-120217-X",
    deweyDecimalCode: "810.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 7",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-120510-X",
    deweyDecimalCode: "815.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 8",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
  {
    isbn: "978-0-120803-X",
    deweyDecimalCode: "819.50",
    bookTitle: "Principles and Advanced Inquiries in MATHEMATICS Volume 8",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 2",
    academicSubjectCategory: "MATHEMATICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for MATHEMATICS scholars."
  },
  {
    isbn: "978-0-121096-X",
    deweyDecimalCode: "824.00",
    bookTitle: "Principles and Advanced Inquiries in CHEMISTRY Volume 8",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 3",
    academicSubjectCategory: "CHEMISTRY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for CHEMISTRY scholars."
  },
  {
    isbn: "978-0-121389-X",
    deweyDecimalCode: "828.50",
    bookTitle: "Principles and Advanced Inquiries in BIOLOGY Volume 8",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 4",
    academicSubjectCategory: "BIOLOGY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for BIOLOGY scholars."
  },
  {
    isbn: "978-0-121682-X",
    deweyDecimalCode: "833.00",
    bookTitle: "Principles and Advanced Inquiries in COMPUTER_SCIENCE Volume 8",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 5",
    academicSubjectCategory: "COMPUTER_SCIENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for COMPUTER_SCIENCE scholars."
  },
  {
    isbn: "978-0-121975-X",
    deweyDecimalCode: "837.50",
    bookTitle: "Principles and Advanced Inquiries in WORLD_LITERATURE Volume 8",
    primaryAuthor: "Prof. Jonathan Fairfax",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack D-Shelf 1",
    academicSubjectCategory: "WORLD_LITERATURE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for WORLD_LITERATURE scholars."
  },
  {
    isbn: "978-0-122268-X",
    deweyDecimalCode: "842.00",
    bookTitle: "Principles and Advanced Inquiries in HISTORY Volume 8",
    primaryAuthor: "Prof. Jonathan Sterling",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack E-Shelf 2",
    academicSubjectCategory: "HISTORY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for HISTORY scholars."
  },
  {
    isbn: "978-0-122561-X",
    deweyDecimalCode: "846.50",
    bookTitle: "Principles and Advanced Inquiries in ECONOMICS Volume 8",
    primaryAuthor: "Prof. Jonathan Blackwood",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack F-Shelf 3",
    academicSubjectCategory: "ECONOMICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for ECONOMICS scholars."
  },
  {
    isbn: "978-0-122854-X",
    deweyDecimalCode: "851.00",
    bookTitle: "Principles and Advanced Inquiries in PHILOSOPHY Volume 8",
    primaryAuthor: "Prof. Jonathan Vance",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack A-Shelf 4",
    academicSubjectCategory: "PHILOSOPHY",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHILOSOPHY scholars."
  },
  {
    isbn: "978-0-123147-X",
    deweyDecimalCode: "855.50",
    bookTitle: "Principles and Advanced Inquiries in GENERAL_REFERENCE Volume 8",
    primaryAuthor: "Prof. Jonathan Holloway",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack B-Shelf 5",
    academicSubjectCategory: "GENERAL_REFERENCE",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for GENERAL_REFERENCE scholars."
  },
  {
    isbn: "978-0-123440-X",
    deweyDecimalCode: "860.00",
    bookTitle: "Principles and Advanced Inquiries in PHYSICS Volume 9",
    primaryAuthor: "Prof. Jonathan Sinclair",
    coAuthors: ["Dr. Sarah Jenkins", "Dr. David Miller"],
    publisherName: "Greenfield Academic University Press",
    editionYear: 2022 + (i % 4),
    totalPrintCopies: 8,
    availableCopies: 5,
    rackLocation: "Rack C-Shelf 1",
    academicSubjectCategory: "PHYSICS",
    summarySynopsis: "Authoritative academic reference manual covering comprehensive foundations, analytical problem sets, and practical experimental investigations for PHYSICS scholars."
  },
];

@Injectable()
export class LibraryCatalogMasterService {
  public getAllBooks(): ComprehensiveLibraryBook[] {
    return MASTER_LIBRARY_BOOKS_CATALOG;
  }

  public getBooksByCategory(category: ComprehensiveLibraryBook['academicSubjectCategory']): ComprehensiveLibraryBook[] {
    return MASTER_LIBRARY_BOOKS_CATALOG.filter(b => b.academicSubjectCategory === category);
  }
}
