import { Injectable } from '@nestjs/common';

export interface InstitutionalEventRecord {
  eventId: string;
  eventCode: string;
  eventTitle: string;
  eventCategory: 'EXAMINATION_PERIOD' | 'ACADEMIC_OLYMPIAD' | 'SPORTS_CHAMPIONSHIP' | 'CULTURAL_FESTIVAL' | 'PARENT_TEACHER_MEETING' | 'STAFF_DEVELOPMENT' | 'INSTITUTIONAL_HOLIDAY';
  startDate: string;
  endDate: string;
  venueLocation: string;
  organizingDepartment: string;
  leadCoordinator: string;
  targetAudience: string[];
  expectedAttendees: number;
  eventSynopsis: string;
}

export const MASTER_ACADEMIC_EVENTS: InstitutionalEventRecord[] = [
  {
    eventId: "EVT-2026-001",
    eventCode: "CAL_EVENT_1",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 1",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-02-02",
    endDate: "2026-02-03",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 315,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-002",
    eventCode: "CAL_EVENT_2",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 2",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-03-03",
    endDate: "2026-03-04",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 330,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-003",
    eventCode: "CAL_EVENT_3",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 3",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-04-04",
    endDate: "2026-04-05",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 345,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-004",
    eventCode: "CAL_EVENT_4",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 4",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-05-05",
    endDate: "2026-05-06",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 360,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-005",
    eventCode: "CAL_EVENT_5",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 5",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-06-06",
    endDate: "2026-06-07",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 375,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-006",
    eventCode: "CAL_EVENT_6",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 6",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-07-07",
    endDate: "2026-07-08",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 390,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-007",
    eventCode: "CAL_EVENT_7",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 7",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-08-08",
    endDate: "2026-08-09",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 405,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-008",
    eventCode: "CAL_EVENT_8",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 8",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-09-09",
    endDate: "2026-09-10",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 420,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-009",
    eventCode: "CAL_EVENT_9",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 9",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-10-10",
    endDate: "2026-10-11",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 435,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-010",
    eventCode: "CAL_EVENT_10",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 10",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-01-11",
    endDate: "2026-01-12",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 450,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-011",
    eventCode: "CAL_EVENT_11",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 11",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-02-12",
    endDate: "2026-02-13",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 465,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-012",
    eventCode: "CAL_EVENT_12",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 12",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-03-13",
    endDate: "2026-03-14",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 480,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-013",
    eventCode: "CAL_EVENT_13",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 13",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-04-14",
    endDate: "2026-04-15",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 495,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-014",
    eventCode: "CAL_EVENT_14",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 14",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-05-15",
    endDate: "2026-05-16",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 510,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-015",
    eventCode: "CAL_EVENT_15",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 15",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-06-16",
    endDate: "2026-06-17",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 525,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-016",
    eventCode: "CAL_EVENT_16",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 16",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-07-17",
    endDate: "2026-07-18",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 540,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-017",
    eventCode: "CAL_EVENT_17",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 17",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-08-18",
    endDate: "2026-08-19",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 555,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-018",
    eventCode: "CAL_EVENT_18",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 18",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-09-19",
    endDate: "2026-09-20",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 570,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-019",
    eventCode: "CAL_EVENT_19",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 19",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-10-20",
    endDate: "2026-10-21",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 585,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-020",
    eventCode: "CAL_EVENT_20",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 20",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-01-21",
    endDate: "2026-01-22",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 600,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-021",
    eventCode: "CAL_EVENT_21",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 21",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-02-22",
    endDate: "2026-02-23",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 615,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-022",
    eventCode: "CAL_EVENT_22",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 22",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-03-23",
    endDate: "2026-03-24",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 630,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-023",
    eventCode: "CAL_EVENT_23",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 23",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-04-24",
    endDate: "2026-04-25",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 645,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-024",
    eventCode: "CAL_EVENT_24",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 24",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-05-25",
    endDate: "2026-05-26",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 660,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-025",
    eventCode: "CAL_EVENT_25",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 25",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-06-26",
    endDate: "2026-06-27",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 675,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-026",
    eventCode: "CAL_EVENT_26",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 26",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-07-01",
    endDate: "2026-07-02",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 690,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-027",
    eventCode: "CAL_EVENT_27",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 27",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-08-02",
    endDate: "2026-08-03",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 705,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-028",
    eventCode: "CAL_EVENT_28",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 28",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-09-03",
    endDate: "2026-09-04",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 720,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-029",
    eventCode: "CAL_EVENT_29",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 29",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-10-04",
    endDate: "2026-10-05",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 735,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-030",
    eventCode: "CAL_EVENT_30",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 30",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-01-05",
    endDate: "2026-01-06",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 750,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-031",
    eventCode: "CAL_EVENT_31",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 31",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-02-06",
    endDate: "2026-02-07",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 765,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-032",
    eventCode: "CAL_EVENT_32",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 32",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-03-07",
    endDate: "2026-03-08",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 780,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-033",
    eventCode: "CAL_EVENT_33",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 33",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-04-08",
    endDate: "2026-04-09",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 795,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-034",
    eventCode: "CAL_EVENT_34",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 34",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 810,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-035",
    eventCode: "CAL_EVENT_35",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 35",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 825,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-036",
    eventCode: "CAL_EVENT_36",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 36",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-07-11",
    endDate: "2026-07-12",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 840,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-037",
    eventCode: "CAL_EVENT_37",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 37",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-08-12",
    endDate: "2026-08-13",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 855,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-038",
    eventCode: "CAL_EVENT_38",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 38",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-09-13",
    endDate: "2026-09-14",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 870,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-039",
    eventCode: "CAL_EVENT_39",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 39",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-10-14",
    endDate: "2026-10-15",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 885,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-040",
    eventCode: "CAL_EVENT_40",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 40",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-01-15",
    endDate: "2026-01-16",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 900,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-041",
    eventCode: "CAL_EVENT_41",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 41",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-02-16",
    endDate: "2026-02-17",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 915,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-042",
    eventCode: "CAL_EVENT_42",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 42",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-03-17",
    endDate: "2026-03-18",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 930,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-043",
    eventCode: "CAL_EVENT_43",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 43",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 945,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-044",
    eventCode: "CAL_EVENT_44",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 44",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-05-19",
    endDate: "2026-05-20",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 960,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-045",
    eventCode: "CAL_EVENT_45",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 45",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-06-20",
    endDate: "2026-06-21",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 975,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-046",
    eventCode: "CAL_EVENT_46",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 46",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-07-21",
    endDate: "2026-07-22",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 990,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-047",
    eventCode: "CAL_EVENT_47",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 47",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-08-22",
    endDate: "2026-08-23",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1005,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-048",
    eventCode: "CAL_EVENT_48",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 48",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-09-23",
    endDate: "2026-09-24",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1020,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-049",
    eventCode: "CAL_EVENT_49",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 49",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-10-24",
    endDate: "2026-10-25",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1035,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-050",
    eventCode: "CAL_EVENT_50",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 50",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-01-25",
    endDate: "2026-01-26",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1050,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-051",
    eventCode: "CAL_EVENT_51",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 51",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-02-26",
    endDate: "2026-02-27",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1065,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-052",
    eventCode: "CAL_EVENT_52",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 52",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-03-01",
    endDate: "2026-03-02",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1080,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-053",
    eventCode: "CAL_EVENT_53",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 53",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-04-02",
    endDate: "2026-04-03",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1095,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-054",
    eventCode: "CAL_EVENT_54",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 54",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-05-03",
    endDate: "2026-05-04",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1110,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-055",
    eventCode: "CAL_EVENT_55",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 55",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-06-04",
    endDate: "2026-06-05",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1125,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-056",
    eventCode: "CAL_EVENT_56",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 56",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-07-05",
    endDate: "2026-07-06",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1140,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-057",
    eventCode: "CAL_EVENT_57",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 57",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-08-06",
    endDate: "2026-08-07",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1155,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-058",
    eventCode: "CAL_EVENT_58",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 58",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-09-07",
    endDate: "2026-09-08",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1170,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-059",
    eventCode: "CAL_EVENT_59",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 59",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-10-08",
    endDate: "2026-10-09",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1185,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-060",
    eventCode: "CAL_EVENT_60",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 60",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-01-09",
    endDate: "2026-01-10",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1200,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-061",
    eventCode: "CAL_EVENT_61",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 61",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-02-10",
    endDate: "2026-02-11",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1215,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-062",
    eventCode: "CAL_EVENT_62",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 62",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-03-11",
    endDate: "2026-03-12",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1230,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-063",
    eventCode: "CAL_EVENT_63",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 63",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-04-12",
    endDate: "2026-04-13",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1245,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-064",
    eventCode: "CAL_EVENT_64",
    eventTitle: "Annual Institutional ACADEMIC OLYMPIAD Event 64",
    eventCategory: "ACADEMIC_OLYMPIAD",
    startDate: "2026-05-13",
    endDate: "2026-05-14",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1260,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-065",
    eventCode: "CAL_EVENT_65",
    eventTitle: "Annual Institutional SPORTS CHAMPIONSHIP Event 65",
    eventCategory: "SPORTS_CHAMPIONSHIP",
    startDate: "2026-06-14",
    endDate: "2026-06-15",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1275,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-066",
    eventCode: "CAL_EVENT_66",
    eventTitle: "Annual Institutional CULTURAL FESTIVAL Event 66",
    eventCategory: "CULTURAL_FESTIVAL",
    startDate: "2026-07-15",
    endDate: "2026-07-16",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1290,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-067",
    eventCode: "CAL_EVENT_67",
    eventTitle: "Annual Institutional PARENT TEACHER MEETING Event 67",
    eventCategory: "PARENT_TEACHER_MEETING",
    startDate: "2026-08-16",
    endDate: "2026-08-17",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1305,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-068",
    eventCode: "CAL_EVENT_68",
    eventTitle: "Annual Institutional STAFF DEVELOPMENT Event 68",
    eventCategory: "STAFF_DEVELOPMENT",
    startDate: "2026-09-17",
    endDate: "2026-09-18",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1320,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-069",
    eventCode: "CAL_EVENT_69",
    eventTitle: "Annual Institutional INSTITUTIONAL HOLIDAY Event 69",
    eventCategory: "INSTITUTIONAL_HOLIDAY",
    startDate: "2026-10-18",
    endDate: "2026-10-19",
    venueLocation: "Greenfield Athletic Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1335,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
  {
    eventId: "EVT-2026-070",
    eventCode: "CAL_EVENT_70",
    eventTitle: "Annual Institutional EXAMINATION PERIOD Event 70",
    eventCategory: "EXAMINATION_PERIOD",
    startDate: "2026-01-19",
    endDate: "2026-01-20",
    venueLocation: "Main Auditorium & Conference Complex",
    organizingDepartment: "Office of the Dean & Academic Directorate",
    leadCoordinator: "Prof. Arthur Vance",
    targetAudience: ["All Enrolled Students", "Faculty Members", "Parent Guardians"],
    expectedAttendees: 1350,
    eventSynopsis: "Comprehensive institutional milestone gathering encouraging scholastic engagement, academic evaluation, and community development across all school divisions."
  },
];

@Injectable()
export class AcademicEventsMasterService {
  public getAllEvents(): InstitutionalEventRecord[] {
    return MASTER_ACADEMIC_EVENTS;
  }

  public getEventsByCategory(category: InstitutionalEventRecord['eventCategory']): InstitutionalEventRecord[] {
    return MASTER_ACADEMIC_EVENTS.filter(e => e.eventCategory === category);
  }
}
