import { Injectable } from '@nestjs/common';

export interface ExamSeatingAllocation {
  seatingId: string;
  examCode: string;
  examTitle: string;
  examDate: string;
  sessionTime: 'MORNING_0900' | 'AFTERNOON_1330';
  hallNumber: string;
  deskNumber: string;
  studentId: string;
  studentName: string;
  rollNumber: string;
  chiefProctorName: string;
  assistantProctorName: string;
}

export const MASTER_EXAM_SEATING_REGISTRY: ExamSeatingAllocation[] = [
  {
    seatingId: "SEAT-EXAM-0001",
    examCode: "EXM-2026-02",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-02",
    studentId: "std-0001",
    studentName: "Student Scholar 1",
    rollNumber: "ROLL-101",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0002",
    examCode: "EXM-2026-03",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-03",
    studentId: "std-0002",
    studentName: "Student Scholar 2",
    rollNumber: "ROLL-102",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0003",
    examCode: "EXM-2026-04",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-04",
    studentId: "std-0003",
    studentName: "Student Scholar 3",
    rollNumber: "ROLL-103",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0004",
    examCode: "EXM-2026-05",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-05",
    studentId: "std-0004",
    studentName: "Student Scholar 4",
    rollNumber: "ROLL-104",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0005",
    examCode: "EXM-2026-06",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-06",
    studentId: "std-0005",
    studentName: "Student Scholar 5",
    rollNumber: "ROLL-105",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0006",
    examCode: "EXM-2026-07",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-07",
    studentId: "std-0006",
    studentName: "Student Scholar 6",
    rollNumber: "ROLL-106",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0007",
    examCode: "EXM-2026-08",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-08",
    studentId: "std-0007",
    studentName: "Student Scholar 7",
    rollNumber: "ROLL-107",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0008",
    examCode: "EXM-2026-09",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-09",
    studentId: "std-0008",
    studentName: "Student Scholar 8",
    rollNumber: "ROLL-108",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0009",
    examCode: "EXM-2026-10",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-10",
    studentId: "std-0009",
    studentName: "Student Scholar 9",
    rollNumber: "ROLL-109",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0010",
    examCode: "EXM-2026-01",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-11",
    studentId: "std-0010",
    studentName: "Student Scholar 10",
    rollNumber: "ROLL-110",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0011",
    examCode: "EXM-2026-02",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-12",
    studentId: "std-0011",
    studentName: "Student Scholar 11",
    rollNumber: "ROLL-111",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0012",
    examCode: "EXM-2026-03",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-13",
    studentId: "std-0012",
    studentName: "Student Scholar 12",
    rollNumber: "ROLL-112",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0013",
    examCode: "EXM-2026-04",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-14",
    studentId: "std-0013",
    studentName: "Student Scholar 13",
    rollNumber: "ROLL-113",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0014",
    examCode: "EXM-2026-05",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-15",
    studentId: "std-0014",
    studentName: "Student Scholar 14",
    rollNumber: "ROLL-114",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0015",
    examCode: "EXM-2026-06",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-16",
    studentId: "std-0015",
    studentName: "Student Scholar 15",
    rollNumber: "ROLL-115",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0016",
    examCode: "EXM-2026-07",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-17",
    studentId: "std-0016",
    studentName: "Student Scholar 16",
    rollNumber: "ROLL-116",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0017",
    examCode: "EXM-2026-08",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-18",
    studentId: "std-0017",
    studentName: "Student Scholar 17",
    rollNumber: "ROLL-117",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0018",
    examCode: "EXM-2026-09",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-19",
    studentId: "std-0018",
    studentName: "Student Scholar 18",
    rollNumber: "ROLL-118",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0019",
    examCode: "EXM-2026-10",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-20",
    studentId: "std-0019",
    studentName: "Student Scholar 19",
    rollNumber: "ROLL-119",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0020",
    examCode: "EXM-2026-01",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-21",
    studentId: "std-0020",
    studentName: "Student Scholar 20",
    rollNumber: "ROLL-120",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0021",
    examCode: "EXM-2026-02",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-22",
    studentId: "std-0021",
    studentName: "Student Scholar 21",
    rollNumber: "ROLL-121",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0022",
    examCode: "EXM-2026-03",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-23",
    studentId: "std-0022",
    studentName: "Student Scholar 22",
    rollNumber: "ROLL-122",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0023",
    examCode: "EXM-2026-04",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-24",
    studentId: "std-0023",
    studentName: "Student Scholar 23",
    rollNumber: "ROLL-123",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0024",
    examCode: "EXM-2026-05",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-25",
    studentId: "std-0024",
    studentName: "Student Scholar 24",
    rollNumber: "ROLL-124",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0025",
    examCode: "EXM-2026-06",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-26",
    studentId: "std-0025",
    studentName: "Student Scholar 25",
    rollNumber: "ROLL-125",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0026",
    examCode: "EXM-2026-07",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-27",
    studentId: "std-0026",
    studentName: "Student Scholar 26",
    rollNumber: "ROLL-126",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0027",
    examCode: "EXM-2026-08",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-28",
    studentId: "std-0027",
    studentName: "Student Scholar 27",
    rollNumber: "ROLL-127",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0028",
    examCode: "EXM-2026-09",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-29",
    studentId: "std-0028",
    studentName: "Student Scholar 28",
    rollNumber: "ROLL-128",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0029",
    examCode: "EXM-2026-10",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-30",
    studentId: "std-0029",
    studentName: "Student Scholar 29",
    rollNumber: "ROLL-129",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0030",
    examCode: "EXM-2026-01",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-01",
    studentId: "std-0030",
    studentName: "Student Scholar 30",
    rollNumber: "ROLL-130",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0031",
    examCode: "EXM-2026-02",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-02",
    studentId: "std-0031",
    studentName: "Student Scholar 31",
    rollNumber: "ROLL-131",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0032",
    examCode: "EXM-2026-03",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-03",
    studentId: "std-0032",
    studentName: "Student Scholar 32",
    rollNumber: "ROLL-132",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0033",
    examCode: "EXM-2026-04",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-04",
    studentId: "std-0033",
    studentName: "Student Scholar 33",
    rollNumber: "ROLL-133",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0034",
    examCode: "EXM-2026-05",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-05",
    studentId: "std-0034",
    studentName: "Student Scholar 34",
    rollNumber: "ROLL-134",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0035",
    examCode: "EXM-2026-06",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-06",
    studentId: "std-0035",
    studentName: "Student Scholar 35",
    rollNumber: "ROLL-135",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0036",
    examCode: "EXM-2026-07",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-07",
    studentId: "std-0036",
    studentName: "Student Scholar 36",
    rollNumber: "ROLL-136",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0037",
    examCode: "EXM-2026-08",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-08",
    studentId: "std-0037",
    studentName: "Student Scholar 37",
    rollNumber: "ROLL-137",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0038",
    examCode: "EXM-2026-09",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-09",
    studentId: "std-0038",
    studentName: "Student Scholar 38",
    rollNumber: "ROLL-138",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0039",
    examCode: "EXM-2026-10",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-10",
    studentId: "std-0039",
    studentName: "Student Scholar 39",
    rollNumber: "ROLL-139",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0040",
    examCode: "EXM-2026-01",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-11",
    studentId: "std-0040",
    studentName: "Student Scholar 40",
    rollNumber: "ROLL-140",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0041",
    examCode: "EXM-2026-02",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-12",
    studentId: "std-0041",
    studentName: "Student Scholar 41",
    rollNumber: "ROLL-141",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0042",
    examCode: "EXM-2026-03",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-13",
    studentId: "std-0042",
    studentName: "Student Scholar 42",
    rollNumber: "ROLL-142",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0043",
    examCode: "EXM-2026-04",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-14",
    studentId: "std-0043",
    studentName: "Student Scholar 43",
    rollNumber: "ROLL-143",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0044",
    examCode: "EXM-2026-05",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-15",
    studentId: "std-0044",
    studentName: "Student Scholar 44",
    rollNumber: "ROLL-144",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0045",
    examCode: "EXM-2026-06",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-16",
    studentId: "std-0045",
    studentName: "Student Scholar 45",
    rollNumber: "ROLL-145",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0046",
    examCode: "EXM-2026-07",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-17",
    studentId: "std-0046",
    studentName: "Student Scholar 46",
    rollNumber: "ROLL-146",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0047",
    examCode: "EXM-2026-08",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-18",
    studentId: "std-0047",
    studentName: "Student Scholar 47",
    rollNumber: "ROLL-147",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0048",
    examCode: "EXM-2026-09",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-19",
    studentId: "std-0048",
    studentName: "Student Scholar 48",
    rollNumber: "ROLL-148",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0049",
    examCode: "EXM-2026-10",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-20",
    studentId: "std-0049",
    studentName: "Student Scholar 49",
    rollNumber: "ROLL-149",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0050",
    examCode: "EXM-2026-01",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-21",
    studentId: "std-0050",
    studentName: "Student Scholar 50",
    rollNumber: "ROLL-150",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0051",
    examCode: "EXM-2026-02",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-22",
    studentId: "std-0051",
    studentName: "Student Scholar 51",
    rollNumber: "ROLL-151",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0052",
    examCode: "EXM-2026-03",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-23",
    studentId: "std-0052",
    studentName: "Student Scholar 52",
    rollNumber: "ROLL-152",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0053",
    examCode: "EXM-2026-04",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-24",
    studentId: "std-0053",
    studentName: "Student Scholar 53",
    rollNumber: "ROLL-153",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0054",
    examCode: "EXM-2026-05",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-25",
    studentId: "std-0054",
    studentName: "Student Scholar 54",
    rollNumber: "ROLL-154",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0055",
    examCode: "EXM-2026-06",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-26",
    studentId: "std-0055",
    studentName: "Student Scholar 55",
    rollNumber: "ROLL-155",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0056",
    examCode: "EXM-2026-07",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-27",
    studentId: "std-0056",
    studentName: "Student Scholar 56",
    rollNumber: "ROLL-156",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0057",
    examCode: "EXM-2026-08",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-28",
    studentId: "std-0057",
    studentName: "Student Scholar 57",
    rollNumber: "ROLL-157",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0058",
    examCode: "EXM-2026-09",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-29",
    studentId: "std-0058",
    studentName: "Student Scholar 58",
    rollNumber: "ROLL-158",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0059",
    examCode: "EXM-2026-10",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-30",
    studentId: "std-0059",
    studentName: "Student Scholar 59",
    rollNumber: "ROLL-159",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0060",
    examCode: "EXM-2026-01",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-01",
    studentId: "std-0060",
    studentName: "Student Scholar 60",
    rollNumber: "ROLL-160",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0061",
    examCode: "EXM-2026-02",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-02",
    studentId: "std-0061",
    studentName: "Student Scholar 61",
    rollNumber: "ROLL-161",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0062",
    examCode: "EXM-2026-03",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-03",
    studentId: "std-0062",
    studentName: "Student Scholar 62",
    rollNumber: "ROLL-162",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0063",
    examCode: "EXM-2026-04",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-04",
    studentId: "std-0063",
    studentName: "Student Scholar 63",
    rollNumber: "ROLL-163",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0064",
    examCode: "EXM-2026-05",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-05",
    studentId: "std-0064",
    studentName: "Student Scholar 64",
    rollNumber: "ROLL-164",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0065",
    examCode: "EXM-2026-06",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-06",
    studentId: "std-0065",
    studentName: "Student Scholar 65",
    rollNumber: "ROLL-165",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0066",
    examCode: "EXM-2026-07",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-07",
    studentId: "std-0066",
    studentName: "Student Scholar 66",
    rollNumber: "ROLL-166",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0067",
    examCode: "EXM-2026-08",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-08",
    studentId: "std-0067",
    studentName: "Student Scholar 67",
    rollNumber: "ROLL-167",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0068",
    examCode: "EXM-2026-09",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-09",
    studentId: "std-0068",
    studentName: "Student Scholar 68",
    rollNumber: "ROLL-168",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0069",
    examCode: "EXM-2026-10",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-10",
    studentId: "std-0069",
    studentName: "Student Scholar 69",
    rollNumber: "ROLL-169",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0070",
    examCode: "EXM-2026-01",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-11",
    studentId: "std-0070",
    studentName: "Student Scholar 70",
    rollNumber: "ROLL-170",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0071",
    examCode: "EXM-2026-02",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-12",
    studentId: "std-0071",
    studentName: "Student Scholar 71",
    rollNumber: "ROLL-171",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0072",
    examCode: "EXM-2026-03",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-13",
    studentId: "std-0072",
    studentName: "Student Scholar 72",
    rollNumber: "ROLL-172",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0073",
    examCode: "EXM-2026-04",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-14",
    studentId: "std-0073",
    studentName: "Student Scholar 73",
    rollNumber: "ROLL-173",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0074",
    examCode: "EXM-2026-05",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-15",
    studentId: "std-0074",
    studentName: "Student Scholar 74",
    rollNumber: "ROLL-174",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0075",
    examCode: "EXM-2026-06",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-16",
    studentId: "std-0075",
    studentName: "Student Scholar 75",
    rollNumber: "ROLL-175",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0076",
    examCode: "EXM-2026-07",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-17",
    studentId: "std-0076",
    studentName: "Student Scholar 76",
    rollNumber: "ROLL-176",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0077",
    examCode: "EXM-2026-08",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-18",
    studentId: "std-0077",
    studentName: "Student Scholar 77",
    rollNumber: "ROLL-177",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0078",
    examCode: "EXM-2026-09",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-19",
    studentId: "std-0078",
    studentName: "Student Scholar 78",
    rollNumber: "ROLL-178",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0079",
    examCode: "EXM-2026-10",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-20",
    studentId: "std-0079",
    studentName: "Student Scholar 79",
    rollNumber: "ROLL-179",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0080",
    examCode: "EXM-2026-01",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-21",
    studentId: "std-0080",
    studentName: "Student Scholar 80",
    rollNumber: "ROLL-180",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0081",
    examCode: "EXM-2026-02",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-22",
    studentId: "std-0081",
    studentName: "Student Scholar 81",
    rollNumber: "ROLL-181",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0082",
    examCode: "EXM-2026-03",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-23",
    studentId: "std-0082",
    studentName: "Student Scholar 82",
    rollNumber: "ROLL-182",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0083",
    examCode: "EXM-2026-04",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-24",
    studentId: "std-0083",
    studentName: "Student Scholar 83",
    rollNumber: "ROLL-183",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0084",
    examCode: "EXM-2026-05",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-25",
    studentId: "std-0084",
    studentName: "Student Scholar 84",
    rollNumber: "ROLL-184",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0085",
    examCode: "EXM-2026-06",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-26",
    studentId: "std-0085",
    studentName: "Student Scholar 85",
    rollNumber: "ROLL-185",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0086",
    examCode: "EXM-2026-07",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-27",
    studentId: "std-0086",
    studentName: "Student Scholar 86",
    rollNumber: "ROLL-186",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0087",
    examCode: "EXM-2026-08",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-13",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-28",
    studentId: "std-0087",
    studentName: "Student Scholar 87",
    rollNumber: "ROLL-187",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0088",
    examCode: "EXM-2026-09",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-14",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-29",
    studentId: "std-0088",
    studentName: "Student Scholar 88",
    rollNumber: "ROLL-188",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0089",
    examCode: "EXM-2026-10",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-15",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-30",
    studentId: "std-0089",
    studentName: "Student Scholar 89",
    rollNumber: "ROLL-189",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0090",
    examCode: "EXM-2026-01",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-16",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-01",
    studentId: "std-0090",
    studentName: "Student Scholar 90",
    rollNumber: "ROLL-190",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0091",
    examCode: "EXM-2026-02",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-17",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-02",
    studentId: "std-0091",
    studentName: "Student Scholar 91",
    rollNumber: "ROLL-191",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0092",
    examCode: "EXM-2026-03",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-18",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-03",
    studentId: "std-0092",
    studentName: "Student Scholar 92",
    rollNumber: "ROLL-192",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0093",
    examCode: "EXM-2026-04",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-19",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-04",
    studentId: "std-0093",
    studentName: "Student Scholar 93",
    rollNumber: "ROLL-193",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0094",
    examCode: "EXM-2026-05",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-20",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-05",
    studentId: "std-0094",
    studentName: "Student Scholar 94",
    rollNumber: "ROLL-194",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0095",
    examCode: "EXM-2026-06",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-21",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 6 (Building C)",
    deskNumber: "DESK-06",
    studentId: "std-0095",
    studentName: "Student Scholar 95",
    rollNumber: "ROLL-195",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0096",
    examCode: "EXM-2026-07",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-22",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 1 (Building A)",
    deskNumber: "DESK-07",
    studentId: "std-0096",
    studentName: "Student Scholar 96",
    rollNumber: "ROLL-196",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0097",
    examCode: "EXM-2026-08",
    examTitle: "Mathematics Advanced Calculus",
    examDate: "2026-10-23",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 2 (Building B)",
    deskNumber: "DESK-08",
    studentId: "std-0097",
    studentName: "Student Scholar 97",
    rollNumber: "ROLL-197",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0098",
    examCode: "EXM-2026-09",
    examTitle: "Chemistry Organic Analysis",
    examDate: "2026-10-10",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 3 (Building C)",
    deskNumber: "DESK-09",
    studentId: "std-0098",
    studentName: "Student Scholar 98",
    rollNumber: "ROLL-198",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0099",
    examCode: "EXM-2026-10",
    examTitle: "Computer Science Practical",
    examDate: "2026-10-11",
    sessionTime: "AFTERNOON_1330",
    hallNumber: "Exam Hall 4 (Building A)",
    deskNumber: "DESK-10",
    studentId: "std-0099",
    studentName: "Student Scholar 99",
    rollNumber: "ROLL-199",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
  {
    seatingId: "SEAT-EXAM-0100",
    examCode: "EXM-2026-01",
    examTitle: "Physics Mid-Term Examination",
    examDate: "2026-10-12",
    sessionTime: "MORNING_0900",
    hallNumber: "Exam Hall 5 (Building B)",
    deskNumber: "DESK-11",
    studentId: "std-0100",
    studentName: "Student Scholar 100",
    rollNumber: "ROLL-200",
    chiefProctorName: "Dr. Arthur Vance (Senior Academic Board)",
    assistantProctorName: "Prof. Sarah Jenkins"
  },
];

@Injectable()
export class ExamSeatingMatrixService {
  public getAllSeatings(): ExamSeatingAllocation[] {
    return MASTER_EXAM_SEATING_REGISTRY;
  }

  public getSeatingsByStudent(studentId: string): ExamSeatingAllocation[] {
    return MASTER_EXAM_SEATING_REGISTRY.filter(s => s.studentId === studentId);
  }
}
