import { Injectable } from '@nestjs/common';

export interface GradeFeeStructureBreakdown {
  structureId: string;
  academicYear: string;
  gradeLevel: string;
  termName: 'TERM_1_AUTUMN' | 'TERM_2_SPRING' | 'TERM_3_SUMMER';
  tuitionFeeUSD: number;
  scienceLabFeeUSD: number;
  computerTechFeeUSD: number;
  libraryResourceFeeUSD: number;
  athleticSportsFeeUSD: number;
  campusFacilityFeeUSD: number;
  totalTermPayableUSD: number;
  duePaymentDeadline: string;
  latePenaltyPerDayUSD: number;
}

export const MASTER_GRADE_FEE_STRUCTURES: GradeFeeStructureBreakdown[] = [
  {
    structureId: "FEE-G1-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 1",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1275,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1715,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G1-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 1",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1275,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1715,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G1-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 1",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1275,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1715,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G2-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 2",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1350,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1790,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G2-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 2",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1350,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1790,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G2-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 2",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1350,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1790,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G3-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 3",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1425,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1865,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G3-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 3",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1425,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1865,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G3-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 3",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1425,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1865,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G4-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 4",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1500,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1940,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G4-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 4",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1500,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1940,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G4-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 4",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1500,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 1940,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G5-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 5",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1575,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2015,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G5-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 5",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1575,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2015,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G5-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 5",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1575,
    scienceLabFeeUSD: 50,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2015,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G6-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 6",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1650,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2190,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G6-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 6",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1650,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2190,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G6-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 6",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1650,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2190,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G7-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 7",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1725,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2265,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G7-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 7",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1725,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2265,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G7-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 7",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1725,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2265,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G8-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 8",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1800,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2340,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G8-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 8",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1800,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2340,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G8-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 8",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1800,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2340,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G9-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 9",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1875,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2415,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G9-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 9",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1875,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2415,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G9-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 9",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1875,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2415,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G10-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 10",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 1950,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2490,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G10-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 10",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 1950,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2490,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G10-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 10",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 1950,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2490,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G11-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 11",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 2025,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2565,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G11-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 11",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 2025,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2565,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G11-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 11",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 2025,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2565,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G12-TERM_1_AUTUMN",
    academicYear: "2026-2027",
    gradeLevel: "Grade 12",
    termName: "TERM_1_AUTUMN",
    tuitionFeeUSD: 2100,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2640,
    duePaymentDeadline: "2026-09-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G12-TERM_2_SPRING",
    academicYear: "2026-2027",
    gradeLevel: "Grade 12",
    termName: "TERM_2_SPRING",
    tuitionFeeUSD: 2100,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2640,
    duePaymentDeadline: "2026-013-15",
    latePenaltyPerDayUSD: 10
  },
  {
    structureId: "FEE-G12-TERM_3_SUMMER",
    academicYear: "2026-2027",
    gradeLevel: "Grade 12",
    termName: "TERM_3_SUMMER",
    tuitionFeeUSD: 2100,
    scienceLabFeeUSD: 150,
    computerTechFeeUSD: 120,
    libraryResourceFeeUSD: 80,
    athleticSportsFeeUSD: 100,
    campusFacilityFeeUSD: 90,
    totalTermPayableUSD: 2640,
    duePaymentDeadline: "2026-017-15",
    latePenaltyPerDayUSD: 10
  },
];

@Injectable()
export class GradeFeeStructureMasterService {
  public getAllFeeStructures(): GradeFeeStructureBreakdown[] {
    return MASTER_GRADE_FEE_STRUCTURES;
  }

  public getFeeByGradeAndTerm(gradeLevel: string, termName: GradeFeeStructureBreakdown['termName']): GradeFeeStructureBreakdown | undefined {
    return MASTER_GRADE_FEE_STRUCTURES.find(f => f.gradeLevel === gradeLevel && f.termName === termName);
  }
}
