import { Injectable } from '@nestjs/common';

export interface ComprehensiveJournalEntry {
  entryNumber: string;
  postingDate: string;
  sourceDocumentRef: string;
  transactionCategory: 'TUITION_BILLING' | 'PAYROLL_DISBURSEMENT' | 'SUPPLIES_PURCHASE' | 'SCHOLARSHIP_GRANT' | 'FACILITY_MAINTENANCE' | 'TRANSPORT_EXPENSE' | 'CAFETERIA_REVENUE' | 'ENDOWMENT_RECEIPT';
  debitAccountCode: string;
  debitAccountName: string;
  creditAccountCode: string;
  creditAccountName: string;
  amountUSD: number;
  narration: string;
  authorizingOfficer: string;
  auditVerificationHash: string;
}

export const MASTER_FINANCIAL_TRANSACTIONS: ComprehensiveJournalEntry[] = [
  {
    entryNumber: "JV-2026-0001",
    postingDate: "2026-08-02",
    sourceDocumentRef: "DOC-REF-117",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 637,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 1 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-26F5"
  },
  {
    entryNumber: "JV-2026-0002",
    postingDate: "2026-08-03",
    sourceDocumentRef: "DOC-REF-234",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 774,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 2 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-4DEA"
  },
  {
    entryNumber: "JV-2026-0003",
    postingDate: "2026-08-04",
    sourceDocumentRef: "DOC-REF-351",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 911,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 3 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-74DF"
  },
  {
    entryNumber: "JV-2026-0004",
    postingDate: "2026-08-05",
    sourceDocumentRef: "DOC-REF-468",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 1048,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 4 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-9BD4"
  },
  {
    entryNumber: "JV-2026-0005",
    postingDate: "2026-08-06",
    sourceDocumentRef: "DOC-REF-585",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 1185,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 5 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-C2C9"
  },
  {
    entryNumber: "JV-2026-0006",
    postingDate: "2026-08-07",
    sourceDocumentRef: "DOC-REF-702",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 1322,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 6 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-E9BE"
  },
  {
    entryNumber: "JV-2026-0007",
    postingDate: "2026-08-08",
    sourceDocumentRef: "DOC-REF-819",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 1459,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 7 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-110B3"
  },
  {
    entryNumber: "JV-2026-0008",
    postingDate: "2026-08-09",
    sourceDocumentRef: "DOC-REF-936",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 1596,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 8 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-137A8"
  },
  {
    entryNumber: "JV-2026-0009",
    postingDate: "2026-08-10",
    sourceDocumentRef: "DOC-REF-1053",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 1733,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 9 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-15E9D"
  },
  {
    entryNumber: "JV-2026-0010",
    postingDate: "2026-08-11",
    sourceDocumentRef: "DOC-REF-1170",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 1870,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 10 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-18592"
  },
  {
    entryNumber: "JV-2026-0011",
    postingDate: "2026-08-12",
    sourceDocumentRef: "DOC-REF-1287",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 2007,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 11 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-1AC87"
  },
  {
    entryNumber: "JV-2026-0012",
    postingDate: "2026-08-13",
    sourceDocumentRef: "DOC-REF-1404",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 2144,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 12 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-1D37C"
  },
  {
    entryNumber: "JV-2026-0013",
    postingDate: "2026-08-14",
    sourceDocumentRef: "DOC-REF-1521",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 2281,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 13 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-1FA71"
  },
  {
    entryNumber: "JV-2026-0014",
    postingDate: "2026-08-15",
    sourceDocumentRef: "DOC-REF-1638",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 2418,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 14 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-22166"
  },
  {
    entryNumber: "JV-2026-0015",
    postingDate: "2026-08-16",
    sourceDocumentRef: "DOC-REF-1755",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 2555,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 15 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-2485B"
  },
  {
    entryNumber: "JV-2026-0016",
    postingDate: "2026-08-17",
    sourceDocumentRef: "DOC-REF-1872",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 2692,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 16 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-26F50"
  },
  {
    entryNumber: "JV-2026-0017",
    postingDate: "2026-08-18",
    sourceDocumentRef: "DOC-REF-1989",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 2829,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 17 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-29645"
  },
  {
    entryNumber: "JV-2026-0018",
    postingDate: "2026-08-19",
    sourceDocumentRef: "DOC-REF-2106",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 2966,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 18 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-2BD3A"
  },
  {
    entryNumber: "JV-2026-0019",
    postingDate: "2026-08-20",
    sourceDocumentRef: "DOC-REF-2223",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 3103,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 19 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-2E42F"
  },
  {
    entryNumber: "JV-2026-0020",
    postingDate: "2026-08-21",
    sourceDocumentRef: "DOC-REF-2340",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 3240,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 20 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-30B24"
  },
  {
    entryNumber: "JV-2026-0021",
    postingDate: "2026-08-22",
    sourceDocumentRef: "DOC-REF-2457",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 3377,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 21 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-33219"
  },
  {
    entryNumber: "JV-2026-0022",
    postingDate: "2026-08-23",
    sourceDocumentRef: "DOC-REF-2574",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 3514,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 22 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-3590E"
  },
  {
    entryNumber: "JV-2026-0023",
    postingDate: "2026-08-24",
    sourceDocumentRef: "DOC-REF-2691",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 3651,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 23 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-38003"
  },
  {
    entryNumber: "JV-2026-0024",
    postingDate: "2026-08-25",
    sourceDocumentRef: "DOC-REF-2808",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 3788,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 24 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-3A6F8"
  },
  {
    entryNumber: "JV-2026-0025",
    postingDate: "2026-08-26",
    sourceDocumentRef: "DOC-REF-2925",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 3925,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 25 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-3CDED"
  },
  {
    entryNumber: "JV-2026-0026",
    postingDate: "2026-08-27",
    sourceDocumentRef: "DOC-REF-3042",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 4062,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 26 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-3F4E2"
  },
  {
    entryNumber: "JV-2026-0027",
    postingDate: "2026-08-28",
    sourceDocumentRef: "DOC-REF-3159",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 4199,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 27 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-41BD7"
  },
  {
    entryNumber: "JV-2026-0028",
    postingDate: "2026-08-01",
    sourceDocumentRef: "DOC-REF-3276",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 4336,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 28 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-442CC"
  },
  {
    entryNumber: "JV-2026-0029",
    postingDate: "2026-08-02",
    sourceDocumentRef: "DOC-REF-3393",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 4473,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 29 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-469C1"
  },
  {
    entryNumber: "JV-2026-0030",
    postingDate: "2026-08-03",
    sourceDocumentRef: "DOC-REF-3510",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 4610,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 30 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-490B6"
  },
  {
    entryNumber: "JV-2026-0031",
    postingDate: "2026-08-04",
    sourceDocumentRef: "DOC-REF-3627",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 4747,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 31 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-4B7AB"
  },
  {
    entryNumber: "JV-2026-0032",
    postingDate: "2026-08-05",
    sourceDocumentRef: "DOC-REF-3744",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 4884,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 32 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-4DEA0"
  },
  {
    entryNumber: "JV-2026-0033",
    postingDate: "2026-08-06",
    sourceDocumentRef: "DOC-REF-3861",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 5021,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 33 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-50595"
  },
  {
    entryNumber: "JV-2026-0034",
    postingDate: "2026-08-07",
    sourceDocumentRef: "DOC-REF-3978",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 5158,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 34 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-52C8A"
  },
  {
    entryNumber: "JV-2026-0035",
    postingDate: "2026-08-08",
    sourceDocumentRef: "DOC-REF-4095",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 5295,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 35 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-5537F"
  },
  {
    entryNumber: "JV-2026-0036",
    postingDate: "2026-08-09",
    sourceDocumentRef: "DOC-REF-4212",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 5432,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 36 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-57A74"
  },
  {
    entryNumber: "JV-2026-0037",
    postingDate: "2026-08-10",
    sourceDocumentRef: "DOC-REF-4329",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 5569,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 37 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-5A169"
  },
  {
    entryNumber: "JV-2026-0038",
    postingDate: "2026-08-11",
    sourceDocumentRef: "DOC-REF-4446",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 5706,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 38 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-5C85E"
  },
  {
    entryNumber: "JV-2026-0039",
    postingDate: "2026-08-12",
    sourceDocumentRef: "DOC-REF-4563",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 5843,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 39 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-5EF53"
  },
  {
    entryNumber: "JV-2026-0040",
    postingDate: "2026-08-13",
    sourceDocumentRef: "DOC-REF-4680",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 5980,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 40 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-61648"
  },
  {
    entryNumber: "JV-2026-0041",
    postingDate: "2026-08-14",
    sourceDocumentRef: "DOC-REF-4797",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 6117,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 41 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-63D3D"
  },
  {
    entryNumber: "JV-2026-0042",
    postingDate: "2026-08-15",
    sourceDocumentRef: "DOC-REF-4914",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 6254,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 42 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-66432"
  },
  {
    entryNumber: "JV-2026-0043",
    postingDate: "2026-08-16",
    sourceDocumentRef: "DOC-REF-5031",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 6391,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 43 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-68B27"
  },
  {
    entryNumber: "JV-2026-0044",
    postingDate: "2026-08-17",
    sourceDocumentRef: "DOC-REF-5148",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 6528,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 44 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-6B21C"
  },
  {
    entryNumber: "JV-2026-0045",
    postingDate: "2026-08-18",
    sourceDocumentRef: "DOC-REF-5265",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 6665,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 45 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-6D911"
  },
  {
    entryNumber: "JV-2026-0046",
    postingDate: "2026-08-19",
    sourceDocumentRef: "DOC-REF-5382",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 6802,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 46 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-70006"
  },
  {
    entryNumber: "JV-2026-0047",
    postingDate: "2026-08-20",
    sourceDocumentRef: "DOC-REF-5499",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 6939,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 47 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-726FB"
  },
  {
    entryNumber: "JV-2026-0048",
    postingDate: "2026-08-21",
    sourceDocumentRef: "DOC-REF-5616",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 7076,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 48 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-74DF0"
  },
  {
    entryNumber: "JV-2026-0049",
    postingDate: "2026-08-22",
    sourceDocumentRef: "DOC-REF-5733",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 7213,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 49 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-774E5"
  },
  {
    entryNumber: "JV-2026-0050",
    postingDate: "2026-08-23",
    sourceDocumentRef: "DOC-REF-5850",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 7350,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 50 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-79BDA"
  },
  {
    entryNumber: "JV-2026-0051",
    postingDate: "2026-08-24",
    sourceDocumentRef: "DOC-REF-5967",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 7487,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 51 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-7C2CF"
  },
  {
    entryNumber: "JV-2026-0052",
    postingDate: "2026-08-25",
    sourceDocumentRef: "DOC-REF-6084",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 7624,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 52 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-7E9C4"
  },
  {
    entryNumber: "JV-2026-0053",
    postingDate: "2026-08-26",
    sourceDocumentRef: "DOC-REF-6201",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 7761,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 53 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-810B9"
  },
  {
    entryNumber: "JV-2026-0054",
    postingDate: "2026-08-27",
    sourceDocumentRef: "DOC-REF-6318",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 7898,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 54 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-837AE"
  },
  {
    entryNumber: "JV-2026-0055",
    postingDate: "2026-08-28",
    sourceDocumentRef: "DOC-REF-6435",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 8035,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 55 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-85EA3"
  },
  {
    entryNumber: "JV-2026-0056",
    postingDate: "2026-08-01",
    sourceDocumentRef: "DOC-REF-6552",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 8172,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 56 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-88598"
  },
  {
    entryNumber: "JV-2026-0057",
    postingDate: "2026-08-02",
    sourceDocumentRef: "DOC-REF-6669",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 8309,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 57 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-8AC8D"
  },
  {
    entryNumber: "JV-2026-0058",
    postingDate: "2026-08-03",
    sourceDocumentRef: "DOC-REF-6786",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 8446,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 58 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-8D382"
  },
  {
    entryNumber: "JV-2026-0059",
    postingDate: "2026-08-04",
    sourceDocumentRef: "DOC-REF-6903",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 8583,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 59 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-8FA77"
  },
  {
    entryNumber: "JV-2026-0060",
    postingDate: "2026-08-05",
    sourceDocumentRef: "DOC-REF-7020",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 8720,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 60 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-9216C"
  },
  {
    entryNumber: "JV-2026-0061",
    postingDate: "2026-08-06",
    sourceDocumentRef: "DOC-REF-7137",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 8857,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 61 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-94861"
  },
  {
    entryNumber: "JV-2026-0062",
    postingDate: "2026-08-07",
    sourceDocumentRef: "DOC-REF-7254",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 8994,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 62 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-96F56"
  },
  {
    entryNumber: "JV-2026-0063",
    postingDate: "2026-08-08",
    sourceDocumentRef: "DOC-REF-7371",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 9131,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 63 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-9964B"
  },
  {
    entryNumber: "JV-2026-0064",
    postingDate: "2026-08-09",
    sourceDocumentRef: "DOC-REF-7488",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 9268,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 64 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-9BD40"
  },
  {
    entryNumber: "JV-2026-0065",
    postingDate: "2026-08-10",
    sourceDocumentRef: "DOC-REF-7605",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 9405,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 65 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-9E435"
  },
  {
    entryNumber: "JV-2026-0066",
    postingDate: "2026-08-11",
    sourceDocumentRef: "DOC-REF-7722",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 9542,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 66 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-A0B2A"
  },
  {
    entryNumber: "JV-2026-0067",
    postingDate: "2026-08-12",
    sourceDocumentRef: "DOC-REF-7839",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 9679,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 67 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-A321F"
  },
  {
    entryNumber: "JV-2026-0068",
    postingDate: "2026-08-13",
    sourceDocumentRef: "DOC-REF-7956",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 9816,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 68 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-A5914"
  },
  {
    entryNumber: "JV-2026-0069",
    postingDate: "2026-08-14",
    sourceDocumentRef: "DOC-REF-8073",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 9953,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 69 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-A8009"
  },
  {
    entryNumber: "JV-2026-0070",
    postingDate: "2026-08-15",
    sourceDocumentRef: "DOC-REF-8190",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 10090,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 70 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-AA6FE"
  },
  {
    entryNumber: "JV-2026-0071",
    postingDate: "2026-08-16",
    sourceDocumentRef: "DOC-REF-8307",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 10227,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 71 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-ACDF3"
  },
  {
    entryNumber: "JV-2026-0072",
    postingDate: "2026-08-17",
    sourceDocumentRef: "DOC-REF-8424",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 10364,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 72 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-AF4E8"
  },
  {
    entryNumber: "JV-2026-0073",
    postingDate: "2026-08-18",
    sourceDocumentRef: "DOC-REF-8541",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 10501,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 73 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-B1BDD"
  },
  {
    entryNumber: "JV-2026-0074",
    postingDate: "2026-08-19",
    sourceDocumentRef: "DOC-REF-8658",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 10638,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 74 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-B42D2"
  },
  {
    entryNumber: "JV-2026-0075",
    postingDate: "2026-08-20",
    sourceDocumentRef: "DOC-REF-8775",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 10775,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 75 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-B69C7"
  },
  {
    entryNumber: "JV-2026-0076",
    postingDate: "2026-08-21",
    sourceDocumentRef: "DOC-REF-8892",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 10912,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 76 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-B90BC"
  },
  {
    entryNumber: "JV-2026-0077",
    postingDate: "2026-08-22",
    sourceDocumentRef: "DOC-REF-9009",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 11049,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 77 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-BB7B1"
  },
  {
    entryNumber: "JV-2026-0078",
    postingDate: "2026-08-23",
    sourceDocumentRef: "DOC-REF-9126",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 11186,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 78 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-BDEA6"
  },
  {
    entryNumber: "JV-2026-0079",
    postingDate: "2026-08-24",
    sourceDocumentRef: "DOC-REF-9243",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 11323,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 79 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-C059B"
  },
  {
    entryNumber: "JV-2026-0080",
    postingDate: "2026-08-25",
    sourceDocumentRef: "DOC-REF-9360",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 11460,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 80 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-C2C90"
  },
  {
    entryNumber: "JV-2026-0081",
    postingDate: "2026-08-26",
    sourceDocumentRef: "DOC-REF-9477",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 11597,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 81 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-C5385"
  },
  {
    entryNumber: "JV-2026-0082",
    postingDate: "2026-08-27",
    sourceDocumentRef: "DOC-REF-9594",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 11734,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 82 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-C7A7A"
  },
  {
    entryNumber: "JV-2026-0083",
    postingDate: "2026-08-28",
    sourceDocumentRef: "DOC-REF-9711",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 11871,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 83 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-CA16F"
  },
  {
    entryNumber: "JV-2026-0084",
    postingDate: "2026-08-01",
    sourceDocumentRef: "DOC-REF-9828",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 12008,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 84 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-CC864"
  },
  {
    entryNumber: "JV-2026-0085",
    postingDate: "2026-08-02",
    sourceDocumentRef: "DOC-REF-9945",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 12145,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 85 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-CEF59"
  },
  {
    entryNumber: "JV-2026-0086",
    postingDate: "2026-08-03",
    sourceDocumentRef: "DOC-REF-10062",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 12282,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 86 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-D164E"
  },
  {
    entryNumber: "JV-2026-0087",
    postingDate: "2026-08-04",
    sourceDocumentRef: "DOC-REF-10179",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 12419,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 87 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-D3D43"
  },
  {
    entryNumber: "JV-2026-0088",
    postingDate: "2026-08-05",
    sourceDocumentRef: "DOC-REF-10296",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 12556,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 88 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-D6438"
  },
  {
    entryNumber: "JV-2026-0089",
    postingDate: "2026-08-06",
    sourceDocumentRef: "DOC-REF-10413",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 12693,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 89 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-D8B2D"
  },
  {
    entryNumber: "JV-2026-0090",
    postingDate: "2026-08-07",
    sourceDocumentRef: "DOC-REF-10530",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 12830,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 90 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-DB222"
  },
  {
    entryNumber: "JV-2026-0091",
    postingDate: "2026-08-08",
    sourceDocumentRef: "DOC-REF-10647",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 12967,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 91 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-DD917"
  },
  {
    entryNumber: "JV-2026-0092",
    postingDate: "2026-08-09",
    sourceDocumentRef: "DOC-REF-10764",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 13104,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 92 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-E000C"
  },
  {
    entryNumber: "JV-2026-0093",
    postingDate: "2026-08-10",
    sourceDocumentRef: "DOC-REF-10881",
    transactionCategory: "TRANSPORT_EXPENSE",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 13241,
    narration: "Official institutional transaction for TRANSPORT_EXPENSE voucher index 93 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-E2701"
  },
  {
    entryNumber: "JV-2026-0094",
    postingDate: "2026-08-11",
    sourceDocumentRef: "DOC-REF-10998",
    transactionCategory: "CAFETERIA_REVENUE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 13378,
    narration: "Official institutional transaction for CAFETERIA_REVENUE voucher index 94 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-E4DF6"
  },
  {
    entryNumber: "JV-2026-0095",
    postingDate: "2026-08-12",
    sourceDocumentRef: "DOC-REF-11115",
    transactionCategory: "ENDOWMENT_RECEIPT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 13515,
    narration: "Official institutional transaction for ENDOWMENT_RECEIPT voucher index 95 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-E74EB"
  },
  {
    entryNumber: "JV-2026-0096",
    postingDate: "2026-08-13",
    sourceDocumentRef: "DOC-REF-11232",
    transactionCategory: "TUITION_BILLING",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 13652,
    narration: "Official institutional transaction for TUITION_BILLING voucher index 96 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-E9BE0"
  },
  {
    entryNumber: "JV-2026-0097",
    postingDate: "2026-08-14",
    sourceDocumentRef: "DOC-REF-11349",
    transactionCategory: "PAYROLL_DISBURSEMENT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 13789,
    narration: "Official institutional transaction for PAYROLL_DISBURSEMENT voucher index 97 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-EC2D5"
  },
  {
    entryNumber: "JV-2026-0098",
    postingDate: "2026-08-15",
    sourceDocumentRef: "DOC-REF-11466",
    transactionCategory: "SUPPLIES_PURCHASE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 13926,
    narration: "Official institutional transaction for SUPPLIES_PURCHASE voucher index 98 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-EE9CA"
  },
  {
    entryNumber: "JV-2026-0099",
    postingDate: "2026-08-16",
    sourceDocumentRef: "DOC-REF-11583",
    transactionCategory: "SCHOLARSHIP_GRANT",
    debitAccountCode: "5010",
    debitAccountName: "Instructional Faculty Salaries",
    creditAccountCode: "1020",
    creditAccountName: "Bank Operating Account",
    amountUSD: 14063,
    narration: "Official institutional transaction for SCHOLARSHIP_GRANT voucher index 99 covering fiscal operations.",
    authorizingOfficer: "Arthur Miller (Bursar & Accounts Head)",
    auditVerificationHash: "HASH-GIS-AUDIT-F10BF"
  },
  {
    entryNumber: "JV-2026-0100",
    postingDate: "2026-08-17",
    sourceDocumentRef: "DOC-REF-11700",
    transactionCategory: "FACILITY_MAINTENANCE",
    debitAccountCode: "1020",
    debitAccountName: "Bank Operating Account",
    creditAccountCode: "4010",
    creditAccountName: "Tuition Fee Revenue",
    amountUSD: 14200,
    narration: "Official institutional transaction for FACILITY_MAINTENANCE voucher index 100 covering fiscal operations.",
    authorizingOfficer: "Eleanor Vance (Chief Financial Officer)",
    auditVerificationHash: "HASH-GIS-AUDIT-F37B4"
  },
];

@Injectable()
export class FinancialLedgerTransactionsService {
  public getAllTransactions(): ComprehensiveJournalEntry[] {
    return MASTER_FINANCIAL_TRANSACTIONS;
  }

  public getTransactionsByCategory(category: ComprehensiveJournalEntry['transactionCategory']): ComprehensiveJournalEntry[] {
    return MASTER_FINANCIAL_TRANSACTIONS.filter(t => t.transactionCategory === category);
  }

  public calculateTotalVolume(): { totalDebits: number; totalCredits: number; transactionCount: number } {
    const total = MASTER_FINANCIAL_TRANSACTIONS.reduce((acc, t) => acc + t.amountUSD, 0);
    return {
      totalDebits: total,
      totalCredits: total,
      transactionCount: MASTER_FINANCIAL_TRANSACTIONS.length,
    };
  }
}
