export interface ComprehensiveExamScheduleItem {
  examId: string;
  courseCode: string;
  courseTitle: string;
  gradeLevel: string;
  examDate: string;
  startTime: string;
  durationMinutes: number;
  hallLocation: string;
  chiefProctor: string;
  totalCandidates: number;
}

export const MASTER_EXAM_SCHEDULE_ROSTER: ComprehensiveExamScheduleItem[] = [
  {
    examId: "EXM-SCHED-001",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 1 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-002",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 2 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-003",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 3 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-004",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 4 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-005",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 5 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-006",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 6 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-007",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 7 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-008",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 8 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-009",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 9 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-010",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 10 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-011",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 11 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-012",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 12 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-013",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 13 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-014",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 14 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-015",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 15 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-016",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 16 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-017",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 17 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-018",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 18 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-019",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 19 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-020",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 20 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-021",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 21 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-022",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 22 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-023",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 23 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-024",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 24 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-025",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 25 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-026",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 26 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-027",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 27 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-028",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 28 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-029",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 29 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-030",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 30 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-031",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 31 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-032",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 32 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-033",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 33 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-034",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 34 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-035",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 35 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-036",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 36 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-037",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 37 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-038",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 38 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-039",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 39 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-040",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 40 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-041",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 41 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-042",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 42 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-043",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 43 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-044",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 44 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-045",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 45 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-046",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 46 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-047",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 47 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-048",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 48 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-049",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 49 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-050",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 50 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-051",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 51 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-052",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 52 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-053",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 53 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-054",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 54 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-055",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 55 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-056",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 56 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-057",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 57 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-058",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 58 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-059",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 59 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-060",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 60 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-061",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 61 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-062",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 62 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-063",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 63 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-064",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 64 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-065",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 65 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-066",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 66 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-067",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 67 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-068",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 68 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-069",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 69 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-070",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 70 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-071",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 71 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-072",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 72 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-073",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 73 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-074",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 74 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-075",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 75 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-076",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 76 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-077",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 77 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-078",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 78 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-079",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 79 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-080",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 80 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-081",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 81 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-082",
    courseCode: "CRS-102",
    courseTitle: "Subject Assessment 82 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-083",
    courseCode: "CRS-103",
    courseTitle: "Subject Assessment 83 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-084",
    courseCode: "CRS-104",
    courseTitle: "Subject Assessment 84 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-085",
    courseCode: "CRS-105",
    courseTitle: "Subject Assessment 85 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-086",
    courseCode: "CRS-106",
    courseTitle: "Subject Assessment 86 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 2 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-087",
    courseCode: "CRS-107",
    courseTitle: "Subject Assessment 87 - Midterm Examination",
    gradeLevel: "Grade 12",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 3 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-088",
    courseCode: "CRS-108",
    courseTitle: "Subject Assessment 88 - Midterm Examination",
    gradeLevel: "Grade 9",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 4 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-089",
    courseCode: "CRS-109",
    courseTitle: "Subject Assessment 89 - Midterm Examination",
    gradeLevel: "Grade 10",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 5 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
  {
    examId: "EXM-SCHED-090",
    courseCode: "CRS-101",
    courseTitle: "Subject Assessment 90 - Midterm Examination",
    gradeLevel: "Grade 11",
    examDate: "2026-10-15",
    startTime: "09:00 AM",
    durationMinutes: 120,
    hallLocation: "Exam Hall 1 (Building A)",
    chiefProctor: "Dr. Arthur Vance",
    totalCandidates: 35
  },
];

export class ExaminationRosterService {
  public static getAllExams(): ComprehensiveExamScheduleItem[] {
    return MASTER_EXAM_SCHEDULE_ROSTER;
  }
}
