export interface DetailedStaffMember {
  staffId: string;
  fullName: string;
  department: string;
  primarySubject: string;
  qualification: string;
  yearsOfExperience: number;
  assignedClasses: string[];
  contactEmail: string;
  contactPhone: string;
  workloadWeeklyPeriods: number;
}

export const MASTER_STAFF_DIRECTORY: DetailedStaffMember[] = [
  {
    staffId: "STF-001",
    fullName: "David Miller",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller1@greenfield.edu",
    contactPhone: "+1 (555) 234-1001",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-002",
    fullName: "Michael Chang",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang2@greenfield.edu",
    contactPhone: "+1 (555) 234-1002",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-003",
    fullName: "Elena Rostova",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova3@greenfield.edu",
    contactPhone: "+1 (555) 234-1003",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-004",
    fullName: "Robert Davis",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis4@greenfield.edu",
    contactPhone: "+1 (555) 234-1004",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-005",
    fullName: "Jennifer Taylor",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor5@greenfield.edu",
    contactPhone: "+1 (555) 234-1005",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-006",
    fullName: "Arthur Vance",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 11,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance6@greenfield.edu",
    contactPhone: "+1 (555) 234-1006",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-007",
    fullName: "Sophia Sterling",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 12,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling7@greenfield.edu",
    contactPhone: "+1 (555) 234-1007",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-008",
    fullName: "Thomas Anderson",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 13,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson8@greenfield.edu",
    contactPhone: "+1 (555) 234-1008",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-009",
    fullName: "Grace Wilson",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 14,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson9@greenfield.edu",
    contactPhone: "+1 (555) 234-1009",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-010",
    fullName: "Sarah Jenkins",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 15,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins10@greenfield.edu",
    contactPhone: "+1 (555) 234-1010",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-011",
    fullName: "David Miller",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 16,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller11@greenfield.edu",
    contactPhone: "+1 (555) 234-1011",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-012",
    fullName: "Michael Chang",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 17,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang12@greenfield.edu",
    contactPhone: "+1 (555) 234-1012",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-013",
    fullName: "Elena Rostova",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 18,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova13@greenfield.edu",
    contactPhone: "+1 (555) 234-1013",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-014",
    fullName: "Robert Davis",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 19,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis14@greenfield.edu",
    contactPhone: "+1 (555) 234-1014",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-015",
    fullName: "Jennifer Taylor",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 5,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor15@greenfield.edu",
    contactPhone: "+1 (555) 234-1015",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-016",
    fullName: "Arthur Vance",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance16@greenfield.edu",
    contactPhone: "+1 (555) 234-1016",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-017",
    fullName: "Sophia Sterling",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling17@greenfield.edu",
    contactPhone: "+1 (555) 234-1017",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-018",
    fullName: "Thomas Anderson",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson18@greenfield.edu",
    contactPhone: "+1 (555) 234-1018",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-019",
    fullName: "Grace Wilson",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson19@greenfield.edu",
    contactPhone: "+1 (555) 234-1019",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-020",
    fullName: "Sarah Jenkins",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins20@greenfield.edu",
    contactPhone: "+1 (555) 234-1020",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-021",
    fullName: "David Miller",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 11,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller21@greenfield.edu",
    contactPhone: "+1 (555) 234-1021",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-022",
    fullName: "Michael Chang",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 12,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang22@greenfield.edu",
    contactPhone: "+1 (555) 234-1022",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-023",
    fullName: "Elena Rostova",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 13,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova23@greenfield.edu",
    contactPhone: "+1 (555) 234-1023",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-024",
    fullName: "Robert Davis",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 14,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis24@greenfield.edu",
    contactPhone: "+1 (555) 234-1024",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-025",
    fullName: "Jennifer Taylor",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 15,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor25@greenfield.edu",
    contactPhone: "+1 (555) 234-1025",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-026",
    fullName: "Arthur Vance",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 16,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance26@greenfield.edu",
    contactPhone: "+1 (555) 234-1026",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-027",
    fullName: "Sophia Sterling",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 17,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling27@greenfield.edu",
    contactPhone: "+1 (555) 234-1027",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-028",
    fullName: "Thomas Anderson",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 18,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson28@greenfield.edu",
    contactPhone: "+1 (555) 234-1028",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-029",
    fullName: "Grace Wilson",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 19,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson29@greenfield.edu",
    contactPhone: "+1 (555) 234-1029",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-030",
    fullName: "Sarah Jenkins",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 5,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins30@greenfield.edu",
    contactPhone: "+1 (555) 234-1030",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-031",
    fullName: "David Miller",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller31@greenfield.edu",
    contactPhone: "+1 (555) 234-1031",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-032",
    fullName: "Michael Chang",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang32@greenfield.edu",
    contactPhone: "+1 (555) 234-1032",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-033",
    fullName: "Elena Rostova",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova33@greenfield.edu",
    contactPhone: "+1 (555) 234-1033",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-034",
    fullName: "Robert Davis",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis34@greenfield.edu",
    contactPhone: "+1 (555) 234-1034",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-035",
    fullName: "Jennifer Taylor",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor35@greenfield.edu",
    contactPhone: "+1 (555) 234-1035",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-036",
    fullName: "Arthur Vance",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 11,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance36@greenfield.edu",
    contactPhone: "+1 (555) 234-1036",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-037",
    fullName: "Sophia Sterling",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 12,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling37@greenfield.edu",
    contactPhone: "+1 (555) 234-1037",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-038",
    fullName: "Thomas Anderson",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 13,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson38@greenfield.edu",
    contactPhone: "+1 (555) 234-1038",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-039",
    fullName: "Grace Wilson",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 14,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson39@greenfield.edu",
    contactPhone: "+1 (555) 234-1039",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-040",
    fullName: "Sarah Jenkins",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 15,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins40@greenfield.edu",
    contactPhone: "+1 (555) 234-1040",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-041",
    fullName: "David Miller",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 16,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller41@greenfield.edu",
    contactPhone: "+1 (555) 234-1041",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-042",
    fullName: "Michael Chang",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 17,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang42@greenfield.edu",
    contactPhone: "+1 (555) 234-1042",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-043",
    fullName: "Elena Rostova",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 18,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova43@greenfield.edu",
    contactPhone: "+1 (555) 234-1043",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-044",
    fullName: "Robert Davis",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 19,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis44@greenfield.edu",
    contactPhone: "+1 (555) 234-1044",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-045",
    fullName: "Jennifer Taylor",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 5,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor45@greenfield.edu",
    contactPhone: "+1 (555) 234-1045",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-046",
    fullName: "Arthur Vance",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance46@greenfield.edu",
    contactPhone: "+1 (555) 234-1046",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-047",
    fullName: "Sophia Sterling",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling47@greenfield.edu",
    contactPhone: "+1 (555) 234-1047",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-048",
    fullName: "Thomas Anderson",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson48@greenfield.edu",
    contactPhone: "+1 (555) 234-1048",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-049",
    fullName: "Grace Wilson",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson49@greenfield.edu",
    contactPhone: "+1 (555) 234-1049",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-050",
    fullName: "Sarah Jenkins",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins50@greenfield.edu",
    contactPhone: "+1 (555) 234-1050",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-051",
    fullName: "David Miller",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 11,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller51@greenfield.edu",
    contactPhone: "+1 (555) 234-1051",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-052",
    fullName: "Michael Chang",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 12,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang52@greenfield.edu",
    contactPhone: "+1 (555) 234-1052",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-053",
    fullName: "Elena Rostova",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 13,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova53@greenfield.edu",
    contactPhone: "+1 (555) 234-1053",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-054",
    fullName: "Robert Davis",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 14,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis54@greenfield.edu",
    contactPhone: "+1 (555) 234-1054",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-055",
    fullName: "Jennifer Taylor",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 15,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor55@greenfield.edu",
    contactPhone: "+1 (555) 234-1055",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-056",
    fullName: "Arthur Vance",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 16,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance56@greenfield.edu",
    contactPhone: "+1 (555) 234-1056",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-057",
    fullName: "Sophia Sterling",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 17,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling57@greenfield.edu",
    contactPhone: "+1 (555) 234-1057",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-058",
    fullName: "Thomas Anderson",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 18,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson58@greenfield.edu",
    contactPhone: "+1 (555) 234-1058",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-059",
    fullName: "Grace Wilson",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 19,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson59@greenfield.edu",
    contactPhone: "+1 (555) 234-1059",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-060",
    fullName: "Sarah Jenkins",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 5,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins60@greenfield.edu",
    contactPhone: "+1 (555) 234-1060",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-061",
    fullName: "David Miller",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller61@greenfield.edu",
    contactPhone: "+1 (555) 234-1061",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-062",
    fullName: "Michael Chang",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang62@greenfield.edu",
    contactPhone: "+1 (555) 234-1062",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-063",
    fullName: "Elena Rostova",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova63@greenfield.edu",
    contactPhone: "+1 (555) 234-1063",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-064",
    fullName: "Robert Davis",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis64@greenfield.edu",
    contactPhone: "+1 (555) 234-1064",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-065",
    fullName: "Jennifer Taylor",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor65@greenfield.edu",
    contactPhone: "+1 (555) 234-1065",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-066",
    fullName: "Arthur Vance",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 11,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance66@greenfield.edu",
    contactPhone: "+1 (555) 234-1066",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-067",
    fullName: "Sophia Sterling",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 12,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling67@greenfield.edu",
    contactPhone: "+1 (555) 234-1067",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-068",
    fullName: "Thomas Anderson",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 13,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson68@greenfield.edu",
    contactPhone: "+1 (555) 234-1068",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-069",
    fullName: "Grace Wilson",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 14,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson69@greenfield.edu",
    contactPhone: "+1 (555) 234-1069",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-070",
    fullName: "Sarah Jenkins",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 15,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins70@greenfield.edu",
    contactPhone: "+1 (555) 234-1070",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-071",
    fullName: "David Miller",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 16,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "david.miller71@greenfield.edu",
    contactPhone: "+1 (555) 234-1071",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-072",
    fullName: "Michael Chang",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 17,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "michael.chang72@greenfield.edu",
    contactPhone: "+1 (555) 234-1072",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-073",
    fullName: "Elena Rostova",
    department: "Mathematics",
    primarySubject: "Mathematics Studies",
    qualification: "M.Sc / Ph.D in Mathematics Education",
    yearsOfExperience: 18,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "elena.rostova73@greenfield.edu",
    contactPhone: "+1 (555) 234-1073",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-074",
    fullName: "Robert Davis",
    department: "Computer Science",
    primarySubject: "Computer Studies",
    qualification: "M.Sc / Ph.D in Computer Education",
    yearsOfExperience: 19,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "robert.davis74@greenfield.edu",
    contactPhone: "+1 (555) 234-1074",
    workloadWeeklyPeriods: 22
  },
  {
    staffId: "STF-075",
    fullName: "Jennifer Taylor",
    department: "Languages & Literature",
    primarySubject: "Languages Studies",
    qualification: "M.Sc / Ph.D in Languages Education",
    yearsOfExperience: 5,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "jennifer.taylor75@greenfield.edu",
    contactPhone: "+1 (555) 234-1075",
    workloadWeeklyPeriods: 23
  },
  {
    staffId: "STF-076",
    fullName: "Arthur Vance",
    department: "Social Sciences",
    primarySubject: "Social Studies",
    qualification: "M.Sc / Ph.D in Social Education",
    yearsOfExperience: 6,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "arthur.vance76@greenfield.edu",
    contactPhone: "+1 (555) 234-1076",
    workloadWeeklyPeriods: 24
  },
  {
    staffId: "STF-077",
    fullName: "Sophia Sterling",
    department: "Chemistry",
    primarySubject: "Chemistry Studies",
    qualification: "M.Sc / Ph.D in Chemistry Education",
    yearsOfExperience: 7,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sophia.sterling77@greenfield.edu",
    contactPhone: "+1 (555) 234-1077",
    workloadWeeklyPeriods: 25
  },
  {
    staffId: "STF-078",
    fullName: "Thomas Anderson",
    department: "Fine Arts",
    primarySubject: "Fine Studies",
    qualification: "M.Sc / Ph.D in Fine Education",
    yearsOfExperience: 8,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "thomas.anderson78@greenfield.edu",
    contactPhone: "+1 (555) 234-1078",
    workloadWeeklyPeriods: 20
  },
  {
    staffId: "STF-079",
    fullName: "Grace Wilson",
    department: "Physical Education",
    primarySubject: "Physical Studies",
    qualification: "M.Sc / Ph.D in Physical Education",
    yearsOfExperience: 9,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "grace.wilson79@greenfield.edu",
    contactPhone: "+1 (555) 234-1079",
    workloadWeeklyPeriods: 21
  },
  {
    staffId: "STF-080",
    fullName: "Sarah Jenkins",
    department: "Physics & Science",
    primarySubject: "Physics Studies",
    qualification: "M.Sc / Ph.D in Physics Education",
    yearsOfExperience: 10,
    assignedClasses: ["Grade 9-A", "Grade 10-A", "Grade 11-Sci"],
    contactEmail: "sarah.jenkins80@greenfield.edu",
    contactPhone: "+1 (555) 234-1080",
    workloadWeeklyPeriods: 22
  },
];

export class StaffDirectoryService {
  public static getAllStaff(): DetailedStaffMember[] {
    return MASTER_STAFF_DIRECTORY;
  }
}
